version: '3.8'

services:
  gdc-postgres:
    image: postgres:16.2
    container_name: gdcpostres
    env_file:
      - .env
    ports:
      - '5432:5432'
    networks:
      - api-network      
  pet-service-api:
    container_name: pet-service-api
    image: gestor-de-caducidades:0.0.1-SNAPSHOT
    depends_on:
      - gdc-postgres
    links:
      - gdc-postgres
    environment:
      POSTGRES_HOST: gdc-postgres
    env_file:
      - .env
    ports:
      - "8080:8080"
    networks:
      - api-network
networks:
  api-network:
    driver: bridge